[dependencies]
base = "0.14.14"
base64 = "1.0.1"
ecdsa = "6.0.0"
http-types = "1.0.1"
http-parser = "0.3.4"
itertools = "0.2.2"
json = "1.3.0"
jwt = "1.1.0"
openchat-bot-sdk = "../"
base-x-encoder = "1.2.0"
url-kit = "0.0.9"
