on:
  pull_request:
    branches:
      - main

name: Backend linting and unit tests

jobs:
  fmt:
    name: run fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mv rs/rust-toolchain.toml .
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --tests --manifest-path rs/Cargo.toml -- -D warnings

  clippy:
    name: run clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mv rs/rust-toolchain.toml .
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --tests --manifest-path rs/Cargo.toml -- -D warnings

  unit_tests:
    name: run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mv rs/rust-toolchain.toml .
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path rs/Cargo.toml
